function fileStruct = loadAllTextFiles()

fileStruct = struct('Vlamda',load('Vlamda.txt'),...
                    'Vprime',load('Vprime.txt'),...
                    'Scone',load('Scone.txt'),...
                    'MacularPigmentODfromSnodderly',load('MacularPigmentODfromSnodderly.txt'),...
                    'McClung_1h_2700K',load('McClung_1h_2700K.txt'),...
                    'spd_McClung_2700K_1lux',load('spd_McClung_2700K_1lux.txt'),...
                    'McClung_1h_6500K',load('McClung_1h_6500K.txt'),...
                    'spd_McClung_6500K_1lux',load('spd_McClung_6500K_1lux.txt'),...
                    'WL_1h_2700K_corr',load('WL_1h_2700K_corr.txt'),...
                    'spd_WL_2700K_1lux',load('spd_WL_2700K_1lux.txt'),...
                    'WL_1h_5600K_corr',load('WL_1h_5600K_corr.txt'),...
                    'spd_WL_5600K_1lux',load('spd_WL_5600K_1lux.txt'),...
                    'Lumileds_1h_3000K',load('Lumileds_1h_3000K.txt'),...
                    'spd_Lumileds_3000K_1lux',load('spd_Lumileds_3000K_1lux.txt'),...
                    'Lumileds_1h_CG',load('Lumileds_1h_CG.txt'),...
                    'spd_Lumileds_CG_1lux',load('spd_Lumileds_CG_1lux.txt'),...
                    'Lumileds_1h_4000K',load('Lumileds_1h_4000K.txt'),...
                    'spd_Lumileds_4000K_1lux',load('spd_Lumileds_4000K_1lux.txt'));

end