function fileStruct = loadAllTextFiles()
[old_thapan_suppressionswavelengths, old_thapan_suppressionsirr, old_thapan_suppressionssupp] = textread('old thapan suppressions.txt', '%f %f %f', 'headerlines', 1);
[old_thapan_suppressions_below500wavelengths, old_thapan_suppressions_below500irr, old_thapan_suppressions_below500supp] = textread('old thapan suppressions below 500.txt', '%f %f %f', 'headerlines', 1);
[old_thapan_suppressions_above500wavelengths, old_thapan_suppressions_above500irr, old_thapan_suppressions_above500supp] = textread('old thapan suppressions above500.txt', '%f %f %f', 'headerlines', 1);
[old_brainard_suppressionswavelengths, old_brainard_suppressionsirr, old_brainard_suppressionssupp] = textread('old brainard suppressions.txt', '%f %f %f', 'headerlines', 1);
[old_brainard_suppressions_below500wavelengths, old_brainard_suppressions_below500irr, old_brainard_suppressions_below500supp] = textread('old brainard suppressions below 500.txt', '%f %f %f', 'headerlines', 1);
[old_brainard_suppressions_above500wavelengths, old_brainard_suppressions_above500irr, old_brainard_suppressions_above500supp] = textread('old brainard suppressions above500.txt', '%f %f %f', 'headerlines', 1);
fileStruct = struct('Vlamda',load('Vlamda.txt'),...
                    'Vprime',load('Vprime.txt'),...
                    'Scone',load('Scone.txt'),...
                    'CIE31by1',load('CIE31by1.txt'),...
                    'MacularPigmentODfromSnodderly',load('MacularPigmentODfromSnodderly.txt'),...
                    'McClung_1h_2700K',load('McClung_1h_2700K.txt'),...
                    'spd_McClung_2700K_1lux',load('spd_McClung_2700K_1lux.txt'),...
                    'McClung_1h_6500K',load('McClung_1h_6500K.txt'),...
                    'spd_McClung_6500K_1lux',load('spd_McClung_6500K_1lux.txt'),...
                    'WL_1h_2700K_corr',load('WL_1h_2700K_corr.txt'),...
                    'spd_WL_2700K_1lux',load('spd_WL_2700K_1lux.txt'),...
                    'WL_1h_5600K_corr',load('WL_1h_5600K_corr.txt'),...
                    'spd_WL_5600K_1lux',load('spd_WL_5600K_1lux.txt'),...
                    'Lumileds_1h_3000K',load('Lumileds_1h_3000K.txt'),...
                    'spd_Lumileds_3000K_1lux',load('spd_Lumileds_3000K_1lux.txt'),...
                    'Lumileds_1h_CG',load('Lumileds_1h_CG.txt'),...
                    'spd_Lumileds_CG_1lux',load('spd_Lumileds_CG_1lux.txt'),...
                    'Lumileds_1h_4000K',load('Lumileds_1h_4000K.txt'),...
                    'spd_Lumileds_4000K_1lux',load('spd_Lumileds_4000K_1lux.txt'),...
                    'MelanopsinWlensBy2nm_02Oct2012',load('MelanopsinWlensBy2nm_02Oct2012.txt'),...
                    'old_thapan_suppressions', struct('Wavelengths',old_thapan_suppressionswavelengths,...
                                                        'Irr',old_thapan_suppressionsirr,...
                                                        'Supp',old_thapan_suppressionssupp),...
                    'old_thapan_suppressions_above500',struct('Wavelengths',old_thapan_suppressions_above500wavelengths,...
                                                        'Irr',old_thapan_suppressions_above500irr,...
                                                        'Supp',old_thapan_suppressions_above500supp),...
                    'old_thapan_suppressions_below500',struct('Wavelengths',old_thapan_suppressions_below500wavelengths,...
                                                        'Irr',old_thapan_suppressions_below500irr,...
                                                        'Supp',old_thapan_suppressions_below500supp),...
                    'old_brainard_suppressions', struct('Wavelengths',old_brainard_suppressionswavelengths,...
                                                        'Irr',old_brainard_suppressionsirr,...
                                                        'Supp',old_brainard_suppressionssupp),...
                    'old_brainard_suppressions_above500',struct('Wavelengths',old_brainard_suppressions_above500wavelengths,...
                                                        'Irr',old_brainard_suppressions_above500irr,...
                                                        'Supp',old_brainard_suppressions_above500supp),...
                    'old_brainard_suppressions_below500',struct('Wavelengths',old_brainard_suppressions_below500wavelengths,...
                                                        'Irr',old_brainard_suppressions_below500irr,...
                                                        'Supp',old_brainard_suppressions_below500supp));

end